/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.util.Date;

/**
 *
 * @author KiewMing
 */
public class scheduleOrder extends javax.swing.JFrame {

    /**
     * Creates new form scheduleOrder
     */
    public scheduleOrder() {
        initComponents();
        
        Date date = new Date();
        //jLabel9.setText(Integer.toString(date.getYear()));
        jLabel9.setText("2017");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 390));
        getContentPane().setLayout(null);

        jLabel1.setText("Schedule Date : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 110, 30);

        jLabel2.setText("Year : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 20, 40, 30);

        jLabel3.setText("Month : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 20, 70, 30);

        jLabel4.setText("Time : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(24, 115, 60, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 250, 160, 30);

        jLabel5.setText("Address : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 60, 30);

        jLabel6.setText("Name : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 60, 30);

        jLabel7.setText("Contact");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 210, 60, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(120, 120, 160, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(120, 170, 160, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(120, 210, 160, 30);

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 310, 50, 25);

        jLabel8.setText("Day : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 20, 40, 30);

        jLabel9.setText("2017");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 20, 60, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 20, 90, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 20, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String scheduleDate = jTextField2.getText()+"/"+jTextField1.getText()+"/"+jLabel9.getText();
        
        goScheduleOrder make = new goScheduleOrder("111" , scheduleDate , jTextField4.getText(), jTextField5.getText() , jTextField6.getText() , jTextField3.getText());
        make.setVisible(true);
        dispose();
        //ScheduleOrder.addScheduleOrder(o);
        //jTextField7.setText(ScheduleOrder.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scheduleOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scheduleOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scheduleOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheduleOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheduleOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
